spring:
 application:
   name: booking-service
 jpa:
   properties:
      hibernate:
          temp:
            use_jdbc_metadata_defaults: false
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect

server:
 port: 8080
